# Give your app a name
spring.application.name=MarketNexus

# 1. Database Connection Credentials (matching your docker-compose)
# Cloud-Ready Database Configuration
# Spring will look for these variables on the cloud server.
# If it doesn't find them, it defaults to your local Docker setup (after the colon)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/local_marketplace}
spring.datasource.username=${DATABASE_USER:root}
spring.datasource.password=${DATABASE_PASSWORD:rootpassword}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Keep Hibernate auto-update on for now so it builds our tables in the cloud
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Tell Spring to use the PostGIS Spatial Dialect
#spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect (no longer needed for latest version of springboot)

# 3. Hibernate Configuration
# 'update' tells Spring to automatically create your database tables based on your code

# 4. Console Logging (Crucial for debugging and showing off to professors)
# This will print the actual SQL commands Spring generates in your console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true